# Generated by Django 3.2.2 on 2021-05-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210514_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('Contributeur', 'Contributeur'), ('Responsable', 'Responsable')], max_length=128),
        ),
    ]
